.gitignore, cache/.gitignore, docs/source/installation.rst, etc/README, examples/etc/config.yaml, examples/linux/systemd/infoset-ng-api.service, examples/linux/systemd/infoset-ng-ingester.service, examples/linux/upstart/infoset-ng-api.conf, examples/linux/upstart/infoset-ng-ingester.conf, infoset/db/db_configuration.py, infoset/utils/configuration.py, infoset/utils/general.py, log/.gitignore, setup.py
=> Fixes issue #14

bin/infoset-ng-api, docs/source/operation.rst, examples/linux/systemd/infoset-ng-api.service, infoset/utils/configuration.py, infoset/utils/general.py, setup.py
=> Made infosetng-api script a daemon

examples/linux/systemd/infoset-ng-api.service, setup.py
Fixes issue #17 
1. Daemon is setup to run under username of user selected by person running the installation script.
2. Nginx / Apache configurations not done. To be added as another issue.
3. Works for systemd only not sysv (which is being phased out with newer Linux versions)
=> Made installation script install daemon scripts to run in production

docs/source/installation.rst, docs/source/operation.rst, setup.py
Fixes issue #23  (Improve installation documentation)
=> Improve installation documentation #23

docs/source/installation.rst, setup.py
=> Fixes issue #25

infoset/api/api.py, infoset/cache/cache.py, infoset/cache/validate.py, infoset/db/db_datapoint.py, infoset/db/db_deviceagent.py, infoset/db/db_orm.py, infoset/test/test_validate_checkdata.py
=> Fixes issue #38 and #37

docs/source/api.rst, infoset/api/api.py, infoset/db/db_datapoint.py
=> Changed /charted to /timeseries in API

examples/apache/apache.conf, examples/nginx/nginx.conf
Added in sample configs for Nginx and Apache web server reverse proxy. Please Review
=> Nginx and Apache sample reverse proxy confs added

bin/tools/prerequisites.py, docs/source/installation.rst, infoset/test/README.rst
Fixes issue #54  : Create a dependency validation script to be run before installation
=> Fixes issue #54  : Create a dependency validation script to be run before installation

docs/source/configuration.rst, docs/source/installation.rst, examples/etc/config.yaml, infoset/test/create_test_config.py, infoset/test/test_configuration.py, infoset/utils/configuration.py, infoset/utils/general.py, requirements.txt, setup.py
Add support for memcached in the configuration #58
=> Add support for memcached in the configuration #58

Jenkinsfile, infoset/test/_do_all_tests.py, infoset/test/_travis_ci_setup.py, infoset/test/test_api_agents.py, infoset/test/test_api_datapoints.py, infoset/test/test_api_deviceagents.py, infoset/test/test_api_devices.py, infoset/test/test_api_lastcontacts.py, infoset/test/test_api_status.py, infoset/test/test_configuration.py, infoset/test/test_db_agent.py, infoset/test/test_db_agentname.py, infoset/test/test_db_billcode.py, infoset/test/test_db_configuration.py, infoset/test/test_db_datapoint.py, infoset/test/test_db_department.py, infoset/test/test_db_device.py, infoset/test/test_db_deviceagent.py, infoset/test/test_db_multitable.py, infoset/test/test_drain_drain.py, infoset/test/test_drain_functions.py, infoset/test/test_general.py, infoset/test/test_validate_checkdata.py, infoset/test/test_validate_checkduplicates.py, infoset/test/test_validate_checkfile.py, infoset/test/test_validate_checkmainkeys.py, infoset/test/test_validate_functions.py, infoset/test/test_validate_validatecache.py
I needed to create a PR with a Jenkins file to see if it works in Jenkins. Please ignore this until I say otherwise
=> Added basic Jenkins file

Jenkinsfile, infoset.py, infoset/test/_do_all_tests.py, infoset/test/_travis_ci_setup.py, infoset/test/test_api_agents.py, infoset/test/test_api_datapoints.py, infoset/test/test_api_deviceagents.py, infoset/test/test_api_devices.py, infoset/test/test_api_lastcontacts.py, infoset/test/test_api_status.py, infoset/test/test_configuration.py, infoset/test/test_db_agent.py, infoset/test/test_db_agentname.py, infoset/test/test_db_billcode.py, infoset/test/test_db_configuration.py, infoset/test/test_db_datapoint.py, infoset/test/test_db_department.py, infoset/test/test_db_device.py, infoset/test/test_db_deviceagent.py, infoset/test/test_db_multitable.py, infoset/test/test_drain_drain.py, infoset/test/test_drain_functions.py, infoset/test/test_general.py, infoset/test/test_validate_checkdata.py, infoset/test/test_validate_checkduplicates.py, infoset/test/test_validate_checkfile.py, infoset/test/test_validate_checkmainkeys.py, infoset/test/test_validate_functions.py, infoset/test/test_validate_validatecache.py
The goal of this PR is to have Jenkins automatically build and deploy automatically when a commit is added to master. For the sake of just checking to see if this works quickly, it will currently deploy it to /home/luke/infoset-ng but that can be changed later once we know it at least works.
=> Jenkins deployment

bin/systemd/infoset-ng-ingester, infoset/api/__init__.py, infoset/api/config_page.py, infoset/api/templates/config.html
Changes made to settings will be written to the config.yaml file
=> Can now update config file through the web ui

infoset/api/schema_agent.py
| Fixed Tickets            | #155.4
| Doc PR                   |no 
Adds the GraphQL schema for Agent to Infoset. Tests for each query and mutation were carried out manually through GraphiQL.
=> Creates GraphQL Schema for Agent

infoset/api/schema_agentname.py
| Fixed Tickets            | #155.5
| Doc PR                   |no 
The graphql schema for AgentName was added to Infoset. Tests for each query and mutation were carried out manually through GraphiQL.
=> Creates GraphQL Schema for AgentName

infoset/api/schema_device.py
| Fixed Tickets            | #155.1
| Doc PR                   |no 
The graphql schema for Device was added to Infoset. Tests for each query and mutation were carried out manually through GraphiQL.
=> Creates GraphQL Schema for Device

infoset/api/schema.py
…tions for each
| Fixed Tickets            | #155
| Doc PR                   | no
Implements the different schemas and adds the query and mutation functions for each. Tests for each query and mutation were carried out manually through GraphiQL.
=> Implements the different Schemas in Infoset

infoset/api/__init__.py
| Fixed Tickets            | #155
| Doc PR                   | no
Links the session to the graphql schemas and rules. Tests for each query and mutation were carried out manually through GraphiQL.
=> GraphQL schema and rules linked to session

infoset/utils/graphene_utils.py
| Major: Breaking Change?  |no 
| Fixed Tickets            | #155
| Doc PR                   | no
Implements a function required to convert inputs into dictionary. Tests were carried out manually through GraphiQL.
=> Adds function to convert Graphene inputs into dictionary

infoset/db/db_orm.py
| Minor: New Feature?      | no
| Tests Added/Pass?        | no
| Fixed Tickets            | no
| Doc PR                   | no
Replaces BLOB type in columns with String. Hardcoded DB used for testing
=> BLOB columns temporarily replaced by String. Hardcoded DB temp use
